micronaut:
  application:
    name: com.kain.pianocheck
  server:
    port: 8080
    cors:
      enabled: true
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: "aEok5Q9FuKljCpUFqNK7T18yxGxCaClQ"
              jws-algorithm: HS256
        generator:
          access-token-expiration: 360000

datasources:
  default:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/piano?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useColumnNamesInFindColumn=true
    username: root
    password: 'root'
    dialect: MYSQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-lifetime: 180000


wechat:
  appid: wx7da451220f27323b
  appsecret: 327dfe29a57b1b1fe51af4c0c93d515d